### ISSUE TITLE
Pro icons not working

### ISSUE THREAD

**Issue by StefanFransen** [fomantic/icon-script#8]
Hi,

I followed the instructions and added the output to my themes folder but the icons are not loading.
I can see the classes being generated and they show up when inspecting the elements.
But the icon isn't loading, even some free icon's won't load.

Example with the 'abacus' icon:
https://screenshotscdn.firefoxusercontent.com/images/8edcab68-4e82-4fb4-aae0-e58e212113ef.png

Can you please look into this?

Thanks.
Stefan Fransen

**Comment by hammy2899** [comment]
@StefanFransen did you include the pro versions of the font files?

**Comment by StefanFransen** [comment]
Yes! Folder looks like this:

```
drwxr-xr-x  9 stefan users  296 Mar  8 14:01 .
drwxr-xr-x  5 stefan users  263 Mar  8 11:46 ..
-rw-------  1 stefan users   57 Mar  8 14:01 .directory
drwxr-xr-x  8 stefan users  163 Mar  8 11:45 .git
-rw-r--r--  1 stefan users  101 Mar  8 11:45 .gitignore
-rw-r--r--  1 stefan users 2.2K Mar  8 11:45 README.md
-rw-r--r--  1 stefan users  530 Mar  8 11:45 config.json
drwxr-xr-x  4 stefan users   52 Mar  8 11:48 dist
drwxr-xr-x 10 stefan users  129 Mar  8 11:47 fontawesome-pro-5.7.2-web
-rw-r--r--  1 stefan users  44M Mar  8 11:46 fontawesome-pro-5.7.2-web.zip
-rw-r--r--  1 stefan users  12K Mar  8 11:45 index.mjs
drwxr-xr-x 58 stefan users 4.0K Mar  8 11:45 node_modules
-rw-r--r--  1 stefan users  16K Mar  8 11:45 package-lock.json
-rw-r--r--  1 stefan users  818 Mar  8 11:45 package.json
drwxr-xr-x  5 stefan users   46 Mar  8 11:45 src
drwxr-xr-x  2 stefan users   84 Mar  8 11:45 static
drwxr-xr-x  3 stefan users   80 Mar  8 11:45 templates
```

**Comment by hammy2899** [comment]
@StefanFransen did you move the font files in the icons script dist directory to SUI/FUI when you built the CSS for your theme?

**Comment by StefanFransen** [comment]
Yes I moved the assets folder to my themes folder.

**Comment by hammy2899** [comment]
@StefanFransen Could you check to see that the correct font files are getting loaded on your site. 

Go to your site open dev tools and go to the `Sources` tab, find the `icons.*` file which is loaded right click and click `Copy link address` then go to that url and replace the extension with `.svg`.
For example `https://fomantic-ui.com/dist/themes/default/assets/fonts/icons.woff2` would become `https://fomantic-ui.com/dist/themes/default/assets/fonts/icons.svg` then view the page source and check if the font family is the pro version as shown below

![image](https://user-images.githubusercontent.com/11588822/54046188-89592c80-41cb-11e9-9880-96d4d7bb61ac.png)

**Comment by StefanFransen** [comment]
They were not at first.

My fontPath wasn't configured correctly at first in the theme.config file.
Changed that and its working now.

Thank you so much for the work you have put into this repo and Semantic UI.
Have a nice weekend.
